version: "3"
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    hostname: "zookeeper"
    container_name: "zookeeper"
    ports:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper_data:/bitnami/zookeeper
  kafka:
    image: docker.io/bitnami/kafka:3
    hostname: "kafka"
    container_name: "kafka"
    ports:
      - "29092:29092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    volumes:
      - ./kafka_data:/bitnami/kafka
    depends_on:
      - zookeeper
  schema:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema
    container_name: schema
    restart: always
    depends_on:
      - kafka
    ports:
      - "8085:8085"
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY_HOST_NAME=schema
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8085
  mysql:
    image: mysql:8.0.27
    hostname: "mysql"
    container_name: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    security_opt:
      - seccomp:unconfined
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
  connect:
    build:
      context: .
      dockerfile: Dockerfile.connect
    container_name: "connect"
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mysql
    volumes:
      - ./tmp:/tmp
